name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.13.1'
          cache: 'npm'
          cache-dependency-path: './www/package-lock.json'

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build WebAssembly
        run: |
          wasm-pack build --target web --release
          # Ensure the pkg directory exists and is populated
          test -d pkg || exit 1

      - name: Setup Frontend Build
        working-directory: ./www
        run: |
          # Update index.html to use type="module, instead of adding it manually for each script tag"
          sed -i 's/<script src="\.\/bootstrap\.js">/<script type="module" src="\.\/bootstrap\.js">/' index.html
          # Clean install dependencies
          npm ci

      - name: Copy WASM files
        run: |
          mkdir -p www/public
          cp -r pkg/* www/public/

      - name: Build Frontend
        working-directory: ./www
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./www/dist
          force_orphan: true
          commit_message: "Deploy to GitHub Pages [skip ci]"